version: '3.8'
services:

  reverse_proxy:
    restart: always
    container_name: reverse_proxy
    image: nginx:1-alpine
    ports:
      - 82:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - techrun-net

  nginx:
    restart: always
    image: nginx:1-alpine
    container_name: webserver
    ports:
      - 8089:80
    volumes:
      - /var/www/html/:/usr/share/nginx/html
    depends_on:
      - reverse_proxy

networks:
  techrun-net:

volumes:
  techrun-log:
  techrun-data:
